#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=combine_trec
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=outputs/combine_trec.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate hype

python scripts/aggregate_trec_metrics.py \
    --metrics1_path /home/scur1744/hypencoder/retrieval_outputs/hypencoder_tasb_freeze/trec19/metrics/per_query_metrics.json \
    --metrics2_path /home/scur1744/hypencoder/retrieval_outputs/hypencoder_tasb_freeze/trec20/metrics/per_query_metrics.json \
    --output_path /home/scur1744/hypencoder/retrieval_outputs/hypencoder_tasb_freeze/trec_combined/