#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=contriever_freeze_retrieve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=05:00:00
#SBATCH --output=outputs/contriever_freeze_retrieve.out
module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export MODEL_NAME_OR_PATH="/scratch-shared/scur1744/models/contriever_freeze_norm/checkpoint-11790" 
export ENCODING_PATH="/scratch-shared/scur1744/encoded_items/contriever_freeze_norm/msmarco-passage"
export RETRIEVAL_DIR="$HOME/hypencoder/retrieval_outputs/contriever_freeze_norm/trec-dl-2019"
mkdir -p "$RETRIEVAL_DIR"

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--ir_dataset_name="msmarco-passage/trec-dl-2019/judged" \
--query_max_length=64

export RETRIEVAL_DIR="$HOME/hypencoder/retrieval_outputs/contriever_freeze_norm/trec-dl-2020"
mkdir -p "$RETRIEVAL_DIR"

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--ir_dataset_name="msmarco-passage/trec-dl-2020/judged" \
--query_max_length=64

python scripts/combine_trec_results.py   \
--retrieval_files \
/home/scur1744/hypencoder/retrieval_outputs/contriever_freeze_norm/trec-dl-2019/retrieved_items.jsonl \
/home/scur1744/hypencoder/retrieval_outputs/contriever_freeze_norm/trec-dl-2020/retrieved_items.jsonl   \
--ir_dataset_names msmarco-passage/trec-dl-2019/judged msmarco-passage/trec-dl-2020/judged   \
--output_dir /home/scur1744/hypencoder/retrieval_outputs/contriever_freeze_norm/trec_combined