#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=contriever_base_retrieve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=2:00:00
#SBATCH --output=outputs/contriever_base_retrieve.out
module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Common Configuration
export MODEL_NAME_OR_PATH="facebook/contriever-msmarco"
export ENCODING_PATH="/scratch-shared/scur1744/encoded_items/contriever_freeze_norm/msmarco-passage"
export OUTPUT_DIR="$HOME/hypencoder/retrieval_outputs/contriever_base_norm/trec-dl-2019"
export IR_DATASET_NAME="msmarco-passage/trec-dl-2019/judged"

mkdir -p "$(dirname "$OUTPUT_DIR")" 

python hypencoder_cb/inference/retrieve_bi_encoder.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$OUTPUT_DIR \
--ir_dataset_name=$IR_DATASET_NAME \
--query_max_length=64 \
--pooling_type="mean" \
--l2_normalize=True

export OUTPUT_DIR="$HOME/hypencoder/retrieval_outputs/contriever_base_norm/trec-dl-2020"
export IR_DATASET_NAME="msmarco-passage/trec-dl-2020/judged"
mkdir -p "$(dirname "$OUTPUT_DIR")" 

python hypencoder_cb/inference/retrieve_bi_encoder.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$OUTPUT_DIR \
--ir_dataset_name=$IR_DATASET_NAME \
--query_max_length=64 \
--pooling_type="mean" \
--l2_normalize=True

python scripts/combine_trec_results.py   \
--retrieval_files \
/home/scur1744/hypencoder/retrieval_outputs/contriever_base_norm/trec-dl-2019/retrieved_items.jsonl \
/home/scur1744/hypencoder/retrieval_outputs/contriever_base_norm/trec-dl-2020/retrieved_items.jsonl   \
--ir_dataset_names msmarco-passage/trec-dl-2019/judged msmarco-passage/trec-dl-2020/judged   \
--output_dir /home/scur1744/hypencoder/retrieval_outputs/contriever_base_norm/trec_combined


