#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=test_embs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=outputs/test_embs_quick.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate hype

export PYTHONUNBUFFERED=1

python scripts/test_embs.py

#export ENCODING_PATH="/tmp/enc_textdual"
#mkdir -p "$ENCODING_PATH"

#python hypencoder_cb/inference/encode.py \
#  --model_name_or_path="/scratch-shared/scur1744/models/contriever_freeze/checkpoint-11790" \
#  --output_path=$ENCODING_PATH \
#  --ir_dataset_name="beir/fiqa/test" \
#  --model_type="text_dual_encoder"

#export ENCODING_PATH="/tmp/enc_hypdual"
#mkdir -p "$ENCODING_PATH" 

#python hypencoder_cb/inference/encode.py \
#  --model_name_or_path="/scratch-shared/scur1744/models/contriever_freeze/checkpoint-11790" \
#  --output_path= $ENCODING_PATH \
#  --ir_dataset_name="beir/fiqa/test" \
#  --model_type="hypencoder_dual_encoder"