#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=convert_format
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:10:00
#SBATCH --output=outputs/convert_format.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# python scripts/convert_format.py \
#     --dataset FollowIR \
#     --input "$HOME/hypencoder/data/FollowIR/train/train.jsonl" \
#     --output "$HOME/hypencoder/data/FollowIR/train/converted_train.jsonl" \
#     --use_instruction

# python scripts/convert_format.py \
#     --dataset TOT \
#     --input "$HOME/hypencoder/data/TOT/train/Books" \
#     --output "$HOME/hypencoder/data/TOT/train/Books/converted_train.jsonl"

# python scripts/convert_format.py \
#     --dataset TOT \
#     --input "$HOME/hypencoder/data/TOT/train/Movies" \
#     --output "$HOME/hypencoder/data/TOT/train/Movies/converted_train.jsonl"

python scripts/concatenate_jsonl.py \
    --input_files "$HOME/hypencoder/data/TOT/train/Books/converted_train.jsonl" \
                  "$HOME/hypencoder/data/TOT/train/Movies/converted_train.jsonl" \
    --output_file "$HOME/hypencoder/data/TOT/train/converted_train.jsonl"

