#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=convert_format
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:20:00
#SBATCH --output=outputs/convert_format.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

python scripts/fit_dataset.py \
--input_file "$HOME/hypencoder/data/FollowIR/train/converted_train.jsonl" \
--output_file "$HOME/hypencoder/data/FollowIR/train/fitted_train.jsonl"