#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=tasb_h_baseline_msmarco_dev
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=14:00:00
#SBATCH --output=outputs/Tobias/tasb_h_msmarco_baseline_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Common Configuration
export MODEL_NAME_OR_PATH="/scratch-shared/scur1744/models/tasb_nofreeze2/checkpoint-11790" 
export ENCODING_PATH="/scratch-shared/scur1744/encoded_items/tasb_freeze/msmarco-passage"
export OUTPUT_DIR="$HOME/hypencoder/retrieval_outputs/baselines/tasb_hypencoder/msmarco_dev_small"
export IR_DATASET_NAME="msmarco-passage/dev/small"

mkdir -p "$(dirname "$OUTPUT_DIR")" 

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$OUTPUT_DIR \
--ir_dataset_name=$IR_DATASET_NAME \
--query_max_length=64