#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=2
#SBATCH --job-name=tot_finetune
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=36
#SBATCH --time=06:00:00
#SBATCH --output=outputs/tot_finetune.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype
export MASTER_PORT=$((RANDOM + 10000))
export MASTER_ADDR=127.0.0.1

torchrun --nproc_per_node=2 \
  --master_port=${MASTER_PORT} \
  hypencoder_cb/train/train.py hypencoder_cb/train/configs/finetune_TOT.yaml