#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=tasb_baseline_msmarco_dev
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=18:00:00
#SBATCH --output=outputs/Tobias/tasb_msmarco_baseline_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Common Configuration
export MODEL_NAME_OR_PATH="/scratch-shared/scur1744/models/tasb_freeze/checkpoint-7859" 
export ENCODING_PATH="/scratch-shared/scur1744/encoded_items/tasb_freeze/msmarco-passage"
export RETRIEVAL_DIR="$HOME/hypencoder/data/baselines/tasb/msmarco_dev_small"
export IR_DATASET_NAME="msmarco-passage/dev/small"

mkdir -p "$(dirname "$OUTPUT_PATH")" 

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--ir_dataset_name=$IR_DATASET_NAME \
--query_max_length=64