#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=tasb_ret_all_attacks_trec19
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=08:00:00
#SBATCH --output=outputs/Tobias/tasb_retrieve_trec19_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Common Configuration
export MODEL_NAME_OR_PATH="sebastian-hofstaetter/distilbert-dot-tas_b-b256-msmarco" 
export ENCODING_PATH="/scratch-shared/scur1744/encoded_items/tasb_freeze/msmarco-passage"
export BASE_DATA_DIR="$HOME/hypencoder/data/adversarial_attack/msmarco_passage_trec_dl_2019_judged"
export BASE_OUTPUT_DIR="$HOME/hypencoder/retrieval_outputs/adversarial/tasb/trec-dl-2019"
export QREL_JSON="$BASE_DATA_DIR/qrels.json"

mkdir -p "$(dirname "$OUTPUT_PATH")" 

# Run retrieval for all attacks using a single script execution (loads index once)
python hypencoder_cb/inference/retrieve_bi_encoder_multiple.py \
    --model_name_or_path=$MODEL_NAME_OR_PATH \
    --encoded_item_path=$ENCODING_PATH \
    --base_data_dir=$BASE_DATA_DIR \
    --base_output_dir=$BASE_OUTPUT_DIR \
    --attack_types  "['synonym', 'paraphrase', 'naturality', 'mispelling', 'ordering']" \
    --qrel_json=$QREL_JSON \
    --query_id_key="id" \
    --query_text_key="text" \
    --query_max_length=64

echo "All retrievals completed."