#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=gen_attacks_trec19
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=outputs/gen_attacks_trec19_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Configuration
export IR_DATASET_NAME="msmarco-passage/trec-dl-2019/judged"
export OUTPUT_DIR="$HOME/hypencoder/data/adversarial_attack"

export CUDA_VISIBLE_DEVICES=""
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export TF_NUM_INTRAOP_THREADS=$SLURM_CPUS_PER_TASK
export TF_NUM_INTEROP_THREADS=1

# Generate all attack types
python scripts/adversarial_attack/attacks.py \
    --ir_dataset_name=$IR_DATASET_NAME \
    --attack_types all \
    --output_dir=$OUTPUT_DIR
