#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=run_encode
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=outputs/run_encode_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export MODEL_NAME_OR_PATH="jfkback/hypencoder.6_layer"        # from huggingface using from_pretrained
export ENCODING_PATH="$HOME/hypencoder/encoded_items/msmarco-passage-dev"    # path to save encoded items
mkdir -p "$ENCODING_PATH"

srun python -u hypencoder_cb/inference/encode.py \
  --model_name_or_path="$MODEL_NAME_OR_PATH" \
  --output_path="$ENCODING_PATH" \
  --ir_dataset_name="msmarco-passage/dev/small"                          # from huggingface, downloaded into .ir_datasets
