#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=be_base_baseline_msmarco_dev
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=18:00:00
#SBATCH --output=outputs/be_base_msmarco_baseline_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# Common Configuration
export MODEL_NAME_OR_PATH="$HOME/hypencoder/models/be_base" 
export ENCODING_PATH="$HOME/hypencoder/encoded_items/be_base/msmarco-passage-dev"
export OUTPUT_DIR="$HOME/hypencoder/retrieval_outputs/baselines/be_base/msmarco_dev_small"
export IR_DATASET_NAME="msmarco-passage/dev/small"

mkdir -p "$(dirname "$OUTPUT_DIR")" 

python hypencoder_cb/inference/retrieve_bi_encoder.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$OUTPUT_DIR \
--ir_dataset_name=$IR_DATASET_NAME \
--query_max_length=64