#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=run_encode
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:40:00
#SBATCH --output=outputs/run_encode_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

srun python -u hypencoder_cb/inference/encode.py \
  --model_name_or_path="jfkback/hypencoder.6_layer" \
  --output_path="$HOME/hypencoder/encoded_items/arguana" \
  --ir_dataset_name="beir/arguana"