#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=encode_be_base
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=27
#SBATCH --time=10:00:00
#SBATCH --output=outputs/encode_bebase_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate hype

export MODEL_NAME_OR_PATH="/scratch-shared/scur1744/models/bebase_instruction_og"
export NAME="bebase_testJ"
export IR_DATASET_NAME="beir/nfcorpus/test"

python hypencoder_cb/inference/retrieve.py \
	--model_name_or_path="$MODEL_NAME_OR_PATH" \
	--model_type="text_dual_encoder" \
	--ir_dataset_name="$IR_DATASET_NAME" \
	--encoded_item_path=/scratch-shared/scur1744/encoded_items/test/bebase_testT \
	--output_dir="$HOME/hypencoder/retrieval_outputs/test/bebase_testJ" \
	--top_k=1000





