#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=tot-dev_retrieve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=outputs/tot-dev_retrieve.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export MODEL_NAME_OR_PATH="jfkback/hypencoder.6_layer"                  # from huggingface using from_pretrained
export ENCODING_PATH="$HOME/hypencoder/encoded_items/tot-dev/zeroshot"      # path to save encoded items
export RETRIEVAL_DIR="$HOME/hypencoder/retrieval_outputs/tot-dev/zeroshot"
mkdir -p "$RETRIEVAL_DIR"

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--ir_dataset_name="trec-tot/2023/dev" \
--metric_names='("nDCG@10", "RR", "nDCG@100")'
