#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=hypencoder_mean_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=04:00:00
#SBATCH --output=outputs/hypencoder_mean_test.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate hype

python hypencoder_cb/inference/encode.py \
	--model_name_or_path="jfkback/hypencoder.6_layer" \
	--ir_dataset_name="beir/nfcorpus/test" \
	--output_path="/scratch-shared/scur1744/encoded_items/hypencoder_mean_test" 

python hypencoder_cb/inference/retrieve.py \
	--model_name_or_path="jfkback/hypencoder.6_layer" \
	--ir_dataset_name="beir/nfcorpus/test" \
	--encoded_item_path=/scratch-shared/scur1744/encoded_items/hypencoder_mean_test \
	--output_dir="$HOME/hypencoder/retrieval_outputs/hypencoder_mean_test" \
	--top_k=1000