#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=encode_be_base
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=27
#SBATCH --time=04:00:00
#SBATCH --output=outputs/encode_bebase_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

# python scripts/be_base/encode_bebase.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--output_path="/scratch-shared/scur1744/encoded_items/bebase_TEST.docs" \
# 	--batch_size=64

# python scripts/be_base/retrieve_bebase_faiss.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--encoded_docs_path=/scratch-shared/scur1744/encoded_items/bebase_TEST.docs \
# 	--output_dir="$HOME/hypencoder/retrieval_outputs/bebase_TEST" \
# 	--top_k=1000


# python hypencoder_cb/inference/encode_bebase.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--output_path="/scratch-shared/scur1744/encoded_items/bebase_TEST" 
# 	--model_type "be_base"

# python hypencoder_cb/inference/retrieve.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--encoded_item_path=/scratch-shared/scur1744/encoded_items/bebase_TEST \
# 	--output_dir="$HOME/hypencoder/retrieval_outputs/bebase_TEST" \
# 	--top_k=1000

python hypencoder_cb/inference/encode.py \
        --model_name_or_path="/scratch-shared/scur1744/models/bebase" \
        --model_type="text_dual_encoder" \
        --output_path="/scratch-shared/scur1744/encoded_items/bebase_TEST" \
		--ir_dataset_name="beir/nfcorpus/test"


# python hypencoder_cb/inference/encode.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--output_path="/scratch-shared/scur1744/encoded_items/bebase_TEST" \
# 	--model_type="text_dual_encoder"

# python hypencoder_cb/inference/retrieve.py \
# 	--model_name_or_path="/scratch-shared/scur1744/models/bebase" \
# 	--ir_dataset_name="beir/nfcorpus/test" \
# 	--encoded_item_path=/scratch-shared/scur1744/encoded_items/bebase_TEST \
# 	--output_dir="$HOME/hypencoder/retrieval_outputs/bebase_TEST" \
# 	--top_k=1000