#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=agg_trec19_20_attacks
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=00:20:00
#SBATCH --output=outputs/aggregate_trec19_20_attacks_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

ATTACK_TYPES=("mispelling" "naturality" "ordering" "paraphrase" "synonym")
# ATTACK_TYPES=("regular")

BASE_DIR="$HOME/hypencoder/retrieval_outputs"
SCRIPT_DIR="$HOME/hypencoder/scripts"

for ATTACK in "${ATTACK_TYPES[@]}"; do
  METRICS19="$BASE_DIR/adversarial/be_base/trec-dl-2019/$ATTACK/metrics/aggregated_metrics.json"
  METRICS20="$BASE_DIR/adversarial/be_base/trec-dl-2020/$ATTACK/metrics/aggregated_metrics.json"
  OUT_DIR="$BASE_DIR/adversarial/be_base/trec-dl-2019_2020/$ATTACK/metrics"
  OUT_FILE="$OUT_DIR/aggregated_metrics.json"

  echo "Aggregating metrics for attack: ${ATTACK}"
  echo "  2019: $METRICS19"
  echo "  2020: $METRICS20"
  echo "  Out : $OUT_FILE"

  mkdir -p "$OUT_DIR"

  python "$SCRIPT_DIR/aggregate_trec_metrics.py" \
    --metrics1_path "$METRICS19" \
    --metrics2_path "$METRICS20" \
    --output_path "$OUT_FILE"
done

echo "All attack-type aggregations completed."