#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=dl_19_typo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=outputs/dl_19_typo_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export IR_DATASET_NAME="msmarco-passage/trec-dl-2019/judged"
export OUTPUT_PATH="$HOME/hypencoder/data/adversarial_attack/trec19_typos.jsonl"
mkdir -p "$(dirname "$OUTPUT_PATH")"

python scripts/adversarial_attack/make_typo_queries.py \
--ir_dataset_name=$IR_DATASET_NAME \
--save_to=$OUTPUT_PATH \
--output_format jsonl

