#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=dl20_typo_retrieve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=05:00:00
#SBATCH --output=outputs/dl20_typo_retrieve_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export MODEL_NAME_OR_PATH="jfkback/hypencoder.6_layer"
export ENCODING_PATH="$HOME/hypencoder/encoded_items/trec-dl-2020"
export RETRIEVAL_DIR="$HOME/hypencoder/retrieval_outputs/adversarial/trec-dl20-typos"
export QUERY_JSONL="$HOME/hypencoder/data/adversarial_attack/msmarco_passage_trec_dl_2020_judged/trec20_query_typos.jsonl"
export QREL_JSON="$HOME/hypencoder/data/adversarial_attack/msmarco_passage_trec_dl_2020_judged/qrels.json"
mkdir -p "$RETRIEVAL_DIR"

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--query_jsonl=$QUERY_JSONL \
--qrel_json=$QREL_JSON \
--query_id_key="id" \
--query_text_key="text" \
--query_max_length=64

