#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=msmarco_typo_retrieve
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=14:00:00
#SBATCH --output=outputs/msmarco_typo_retrieve_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate hype

export MODEL_NAME_OR_PATH="jfkback/hypencoder.6_layer"
export ENCODING_PATH="$HOME/hypencoder/encoded_items/msmarco-passage-dev"
export RETRIEVAL_DIR="$HOME/hypencoder/retrieval_outputs/adversarial/msmarco-passage-dev-typos"
export QUERY_JSONL="$HOME/hypencoder/data/adversarial_attack/msmarco_passage_dev_small/msmarco_dev_query_typos.jsonl"
export QREL_JSON="$HOME/hypencoder/data/adversarial_attack/msmarco_passage_dev_small/qrels.json"

python hypencoder_cb/inference/retrieve.py \
--model_name_or_path=$MODEL_NAME_OR_PATH \
--encoded_item_path=$ENCODING_PATH \
--output_dir=$RETRIEVAL_DIR \
--query_jsonl=$QUERY_JSONL \
--qrel_json=$QREL_JSON \
--query_id_key="id" \
--query_text_key="text" \
--query_max_length=64

